packages:
    # all packages in direct subdirs of packages/
    - "packages/core"
    - "packages/nuxt-app"
    - "packages/next-app"
    # exclude packages that are inside test directories
    - "!**/test/**"
